import cms from '@igloo-be/netlify-cms-core/src';
import { StringControl, StringPreview } from '@igloo-be/netlify-cms-widget-string/src';
import { NumberControl, NumberPreview } from '@igloo-be/netlify-cms-widget-number/src';
import { TextControl, TextPreview } from '@igloo-be/netlify-cms-widget-text/src';
import { ImageControl, ImagePreview } from '@igloo-be/netlify-cms-widget-image/src';
import { FileControl, FilePreview } from '@igloo-be/netlify-cms-widget-file/src';
import { DateControl, DatePreview } from '@igloo-be/netlify-cms-widget-date/src';
import { DateTimeControl, DateTimePreview } from '@igloo-be/netlify-cms-widget-datetime/src';
import { SelectControl, SelectPreview } from '@igloo-be/netlify-cms-widget-select/src';
import { MarkdownControl, MarkdownPreview } from '@igloo-be/netlify-cms-widget-markdown/src';
import { ListControl, ListPreview } from '@igloo-be/netlify-cms-widget-list/src';
import { ObjectControl, ObjectPreview } from '@igloo-be/netlify-cms-widget-object/src';
import { RelationControl, RelationPreview } from '@igloo-be/netlify-cms-widget-relation/src';
import { BooleanControl } from '@igloo-be/netlify-cms-widget-boolean/src';

const { registerWidget } = cms;

registerWidget('string', StringControl, StringPreview);
registerWidget('text', TextControl, TextPreview);
registerWidget('number', NumberControl, NumberPreview);
registerWidget('list', ListControl, ListPreview);
registerWidget('markdown', MarkdownControl, MarkdownPreview);
registerWidget('image', ImageControl, ImagePreview);
registerWidget('file', FileControl, FilePreview);
registerWidget('date', DateControl, DatePreview);
registerWidget('datetime', DateTimeControl, DateTimePreview);
registerWidget('select', SelectControl, SelectPreview);
registerWidget('object', ObjectControl, ObjectPreview);
registerWidget('relation', RelationControl, RelationPreview);
registerWidget('boolean', BooleanControl);
