import cms from '@igloo-be/netlify-cms-core';
import { StringControl, StringPreview } from '@igloo-be/netlify-cms-widget-string';
import { NumberControl, NumberPreview } from '@igloo-be/netlify-cms-widget-number';
import { TextControl, TextPreview } from '@igloo-be/netlify-cms-widget-text';
import { ImageControl, ImagePreview } from '@igloo-be/netlify-cms-widget-image';
import { FileControl, FilePreview } from '@igloo-be/netlify-cms-widget-file';
import { DateControl, DatePreview } from '@igloo-be/netlify-cms-widget-date';
import { DateTimeControl, DateTimePreview } from '@igloo-be/netlify-cms-widget-datetime';
import { SelectControl, SelectPreview } from '@igloo-be/netlify-cms-widget-select';
import { MarkdownControl, MarkdownPreview } from '@igloo-be/netlify-cms-widget-markdown';
import { ListControl, ListPreview } from '@igloo-be/netlify-cms-widget-list';
import { ObjectControl, ObjectPreview } from '@igloo-be/netlify-cms-widget-object';
import { RelationControl, RelationPreview } from '@igloo-be/netlify-cms-widget-relation';
import { BooleanControl } from '@igloo-be/netlify-cms-widget-boolean';

const { registerWidget } = cms;

registerWidget('string', StringControl, StringPreview);
registerWidget('text', TextControl, TextPreview);
registerWidget('number', NumberControl, NumberPreview);
registerWidget('list', ListControl, ListPreview);
registerWidget('markdown', MarkdownControl, MarkdownPreview);
registerWidget('image', ImageControl, ImagePreview);
registerWidget('file', FileControl, FilePreview);
registerWidget('date', DateControl, DatePreview);
registerWidget('datetime', DateTimeControl, DateTimePreview);
registerWidget('select', SelectControl, SelectPreview);
registerWidget('object', ObjectControl, ObjectPreview);
registerWidget('relation', RelationControl, RelationPreview);
registerWidget('boolean', BooleanControl);
